project_id = "ylooqmqmoufqtxvetxuj"

[functions.get-all-users]
verify_jwt = true

[functions.contexto-maestro]
verify_jwt = false

[functions.master-prompt-generator]
verify_jwt = false

[functions.generate-progressive-tasks]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.get-admin-users]
verify_jwt = true

[functions.get-waitlist]
verify_jwt = true

[functions.approve-waitlist-user]
verify_jwt = true

[functions.validate-access-code]
verify_jwt = false