
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Package } from 'lucide-react';

interface DeliverablesEmptyStateProps {
  language: 'en' | 'es';
}

export const DeliverablesEmptyState: React.FC<DeliverablesEmptyStateProps> = ({
  language
}) => {
  const t = {
    en: {
      noDeliverables: "No deliverables yet",
      createFirst: "Deliverables will appear here when generated by the agent"
    },
    es: {
      noDeliverables: "No hay entregables aún",
      createFirst: "Los entregables aparecerán aquí cuando los genere el agente"
    }
  };

  return (
    <Card className="border-dashed border-2 border-slate-200">
      <CardContent className="flex flex-col items-center justify-center py-12">
        <Package className="w-12 h-12 text-slate-400 mb-4" />
        <p className="text-slate-600 font-medium mb-2">{t[language].noDeliverables}</p>
        <p className="text-sm text-slate-500 text-center">
          {t[language].createFirst}
        </p>
      </CardContent>
    </Card>
  );
};
